
const drinksApi = [
  {
    "strDrink": "Monkey Gland",
    "strGlass": "Cocktail glass",
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/94psp81504350690.jpg",
    "strIngredient1": "Gin",
    "strIngredient2": "Benedictine",
    "strIngredient3": "Orange juice",
    "strIngredient4": "Grenadine",
  },
  {
    "strDrink": "Manhattan",
    "strGlass": "Cocktail glass",
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/yk70e31606771240.jpg",
    "strIngredient1": "Sweet Vermouth",
    "strIngredient2": "Bourbon",
    "strIngredient3": "Angostura bitters",
    "strIngredient4": "Ice",
    "strIngredient5": "Maraschino cherry",
    "strIngredient6": "Orange peel",
  },

  {
    "idDrink": "11844",
    "strDrink": "New York Sour",
    "strDrinkAlternate": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Ordinary Drink",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Whiskey sour glass",
    "strInstructions": "Shake blended whiskey, juice of lemon, and powdered sugar with ice and strain into a whiskey sour glass. Float claret on top. Decorate with the half-slice of lemon and the cherry and serve.",
    "strInstructionsES": null,
    "strInstructionsDE": "Gemischten Whiskey, Zitronensaft und Puderzucker mit Eis schütteln und in ein Whiskey-Sourglas abseihen. Schwimmender Bordeaux auf der Oberfläche. Mit der halben Zitronenscheibe und der Kirsche dekorieren und servieren.",
    "strInstructionsFR": null,
    "strInstructionsIT": "Shakerare il whisky miscelato, il succo di limone e lo zucchero a velo con ghiaccio e filtrare in un bicchiere da whisky sour. Versare il vino in cima.Decorare con mezza fetta di limone e la ciliegia e servire.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/61wgch1504882795.jpg",
    "strIngredient1": "Blended whiskey",
    "strIngredient2": "Lemon",
    "strIngredient3": "Sugar",
    "strIngredient4": "Red wine",
    "strIngredient5": "Lemon",
    "strIngredient6": "Cherry",
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "2 oz ",
    "strMeasure2": "Juice of 1/2 ",
    "strMeasure3": "1 tsp ",
    "strMeasure4": " (Claret)\n",
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strImageSource": null,
    "strImageAttribution": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2017-09-08 15:59:55"
  },
  
  {
    "idDrink": "11128",
    "strDrink": "Boston Sidecar",
    "strDrinkAlternate": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Ordinary Drink",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Cocktail glass",
    "strInstructions": "Shake all ingredients with ice, strain into a cocktail glass, and serve.",
    "strInstructionsES": null,
    "strInstructionsDE": "Alle Zutaten mit Eis schütteln, in ein Cocktailglas abseihen und servieren.",
    "strInstructionsFR": null,
    "strInstructionsIT": "Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/qzs5d11504365962.jpg",
    "strIngredient1": "Light rum",
    "strIngredient2": "Brandy",
    "strIngredient3": "Triple sec",
    "strIngredient4": "Lime",
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "3/4 oz ",
    "strMeasure2": "3/4 oz ",
    "strMeasure3": "3/4 oz ",
    "strMeasure4": "Juice of 1/2 ",
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strImageSource": null,
    "strImageAttribution": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2017-09-02 16:26:02"
  },

]

export default drinksApi;